### ISSUE TITLE
Missing Components

### ISSUE THREAD

**Issue by McRoth73** [yashmulgaonkar/halo#1]
I'm gathering the parts to make this and noticed that some pieces are missing from the BOM.  I don't see the 30 pin connector for the Lilygo board, whatever the 4 little cubes next to it the pic of it and the, I'm guessing, LED's around the perimeter of the semicircle board.  There may be others that I don't see.  Can you please add these and confirm that there aren't any other missing components?
Also, I ordered the V1.0 boards, are they going to work now that I see there is are V1.1 boards?

**Comment by yashmulgaonkar** [comment]
Looks like you are looking for the Breakout board.
All relevant files are here:

https://github.com/yashmulgaonkar/halo/blob/main/V1/Hardware/Electrical_Design/Breakout
